#include "arduino_secrets.h"
// DHT11 - Version: Latest
#include <DHT11.h>


/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/4ca42723-0c40-4042-af70-5dc91898fd07

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float humidity;
  float luminosity;
  float moisture;
  float temperature;
  bool water_pump;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

DHT11 dht11(12);
int ldr_pin = 35; 
int moist_pin = 32;
float l_analog;
float luminosity2;
float moistAnalog;
int waterp_pin=27;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  pinMode(ldr_pin, INPUT);
  pinMode(moist_pin, INPUT);
  pinMode(waterp_pin, OUTPUT);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(4);
  ArduinoCloud.printDebugInfo();


}

void loop() {

  ArduinoCloud.update();
  // Your code here
  // Attempt to read the humidity value from the DHT11 sensor.
  humidity = dht11.readHumidity();
  temperature = dht11.readTemperature();
  if (humidity != DHT11::ERROR_CHECKSUM && humidity != DHT11::ERROR_TIMEOUT) {
    Serial.print("Humidity: ");
    Serial.print(humidity);
    Serial.println(" %");
  }
  Serial.print("Temperature: ");
  Serial.print(temperature);
  Serial.println(" %");
  l_analog = analogRead(ldr_pin);
  Serial.print("l_analog: ");
  Serial.print(l_analog);
  luminosity = (l_analog / 4096) * 100;
  Serial.print("Luminosity: ");
  Serial.print(luminosity);
  Serial.println(" %");
  int tempMoist = 0; /* variable to temporarily store moisture value */
  /* make an average of 10 values to be more accurate */
  for (int a = 0; a < 10; a++) {
    tempMoist += analogRead(moist_pin);
    delay(100);
  }
  moistAnalog = tempMoist / 10;
  moisture = (moistAnalog / 4096) * 100;
  Serial.print("Moisture: ");
  Serial.print(moisture);
  Serial.println(" %");
}

/*
  Since WaterPump is READ_WRITE variable, onWaterPumpChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onWaterPumpChange()  {
  // Add your code here to act upon WaterPump change
  if (water_pump){
    digitalWrite(waterp_pin, HIGH);
  }
  else {
    digitalWrite(waterp_pin, LOW);
  }

}