:Author: n-raz-p
:Email:
:Date: 16/04/2024
:Revision: version#
:License: Public Domain

= Project: Greenhouse IoT System

This IoT project involves the use of an ESP32 microcontroller connected to Arduino Cloud to monitor and control various aspects of a greenhouse environment. 

== Step 1: Installation

1. Download the files or view them at the Arduino IoT Plataform (https://create.arduino.cc/editor/n-raz-p/6c210098-bce5-475b-93c0-c5acf8e1dcf1/preview)
2. Upload them at your Arduino IoT Cloud
3. Upload to your project
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch



== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact: natan.razera@gmail.com or 

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name       | Quantity
| R1 | 10k Resistor    | 1       
| L1 | Yellow LED      | 1        
| E1 | ESP32 DevModule | 1        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
